openapi: 3.0.2
info:
  version: "1.0.0"
  title: "Metadata-Submission"

paths:

  /upload:
    post:
      tags:
        - "Source"
      summary: "Uploads a xml file provided by the user'' form input."
      description: "Allows the user to fill up a form associated to a specific xml document type."
      operationId: "upload_file"

      requestBody:
        content:
          file/xml:
            schema:
              type: object
              required:
                - file
              properties:
                doc_type:
                  type: string
                  format: binary

      responses:
        405:
          description: "Invalid input"
        400:
          description: "  - The submitted form is not valid.
                          - Something went wrong with your submission, please check each field's requirements.
                          - This document can not be uploaded since it's not being referenced anywhere
                          - No file keyword in POST request."

        200:
          description: "The file //file of type //file_type was successfully uploaded"

