from os import environ

ENV_NAMESPACE = "CGE_QUERY_API"
LOG_DIR = '.'
HOST = 'MONGODB_HOST'
PORT = 'MONGODB_PORT'
DB = 'METADATADB'
METADATA_COLLECTION = 'METADATA_MONGODB_COLLECTION'

APPLICATION_ROOT: str = environ.get("FLASK_APPLICATION_ROOT", "/")
SERVER_SCHEME: str = environ.get("SERVER_SCHEME", "http")
SERVER_NAME = environ.get("SERVER_NAME")
SECRET_KEY = 'dev'

MONGODB_HOST = environ.get(HOST, 'localhost')
MONGODB_PORT = environ.get(PORT, '27017')
MONGODB_DB = environ.get(DB, "metadatadb")
MONGODB_METADATA_COLLECTION = environ.get(METADATA_COLLECTION, "metadata")
DB_URI = f'mongodb://{MONGODB_HOST}:{MONGODB_PORT}/'
